### ISSUE TITLE
Wrong content Length for big image

### ISSUE THREAD

**Issue by dragopot** [Alamofire/AlamofireImage#126]
Hi,

I didn't have any problem to use this library. However for load an image which is contentLength is 1608489, i got some trouble : 
Error Domain=com.alamofire.error Code=-1016 "Failed to create a valid Image from the response data"

And in  the Content-Length return by the request is : 19

headers {
    "Accept-Ranges" = bytes;
    Connection = "Keep-Alive";
    "Content-Length" = 19;
    "Content-Type" = "image/png";
    Date = "Mon, 27 Jun 2016 12:01:28 GMT";
    Etag = "\"316e17-13-53607e6c35185\"";
    "Keep-Alive" = "timeout=5, max=100";
    "Last-Modified" = "Fri, 24 Jun 2016 15:34:07 GMT";
    Server = Apache;
} })

This is how i load the image : 

 self.profil.af_setImageWithURL(NSURL(string: urlServer! + user.photo!)!, placeholderImage: UIImage(named: "user"), filter: nil, imageTransition: .FlipFromLeft(0.2), completion: { (response) -> Void in
                self.profil.image = response.result.value
                print(response.result.error)
                print(response.response)
                print(response.request)
            })

This the image i try to load : http://jackson.daveo.ovh/uploads/guillaume.duez.png
It s an image import from an Iphone 5s.

**Comment by cnoon** [comment]
Hi @dragopot,

I put together a quick test to see what could be wrong with your image and everything seems to be working properly. Here's the test I put together:

```swift
func testLargeCustomImage() {
    // Given
    let URLString = "http://jackson.daveo.ovh/uploads/guillaume.duez.png"
    let expectation = expectationWithDescription("Request should return PNG response image")

    var response: Response<Image, NSError>?

    // When
    manager.request(.GET, URLString)
        .responseImage { closureResponse in
            response = closureResponse
            expectation.fulfill()
        }

    waitForExpectationsWithTimeout(timeout, handler: nil)

    // Then
    XCTAssertNotNil(response?.request, "request should not be nil")
    XCTAssertNotNil(response?.response, "response should not be nil")
    XCTAssertTrue(response?.result.isSuccess ?? false, "result should be success")

    if let image = response?.result.value {
        print("Image: \(image)")
    } else {
        XCTFail("result image should not be nil")
    }
}
```

If you copy that into the `BaseTestCase` class and run it, you'll see it passes successfully. Because of this, I'm not really sure what to tell you. I'd take a look at the test and try to figure out what's different between that logic and possibly how you're constructing your URL.

I'm going to close this issue out for now. If you track this down further and feel there is something else worth us investigating, please provide more details and we'll happily re-open and investigate further.

Cheers. 🍻
