### ISSUE TITLE
Unable to remove image from cache

### ISSUE THREAD

**Issue by marcmatta** [Alamofire/AlamofireImage#127]
Hi

I'm trying to remove a specific image with no success from image cache using the below API:

`ImageDownloader.defaultInstance.imageCache!.removeImageForRequest(request, withAdditionalIdentifier: nil)`

Although,

`let image = ImageDownloader.defaultInstance.imageCache!.imageForRequest(request, withAdditionalIdentifier: nil)`

does return the cached image.

Any ideas?

Thanks in advance!

**Comment by cnoon** [comment]
Not sure what to tell you @marcmatta. There's not much to go on here. We have a bunch of [tests](https://github.com/Alamofire/AlamofireImage/blob/master/Tests/ImageCacheTests.swift#L138-L188) around this behavior to make sure removal works as expected.

I'd first take a look at those tests to see if there's anything obvious that stands out to you as something you could maybe modify on your end. Then I'd start to troubleshoot to make sure the `request` object you're referring to does have the exact same URL since that's what's used as the unique identifier to store in the cache.

I'm going to close this issue out for now since there's nothing else to go on. If you provide some additional info that leads us to believe there may be an issue in AFI, we'll happily re-open the issue and investigate further.

Cheers. 🍻
