### ISSUE TITLE
Invalid SSL Certificate

### ISSUE THREAD

**Issue by kusalshrestha** [Alamofire/AlamofireImage#134]
Due to invalid SSL certificate I got this ~> " NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)"
I'd bypassed the problem for the Alamofire case as creating an own Manager like:

    static let defaultManager: Alamofire.Manager = {

        let serverTrustPolicies: [String: ServerTrustPolicy] = [
            "<-Invalid SSL url here->": .DisableEvaluation ]
      
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = Alamofire.Manager.defaultHTTPHeaders
        
        return Alamofire.Manager(
            configuration: configuration,
            serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
        )
    }()

p.s: I'm using self signed invalid ssl certificate
#### How to deal with this?

**Comment by kusalshrestha** [comment]
`asdfghj`

**Comment by kusalshrestha** [comment]
@cnoon @kcharwood @AnthonyMDev Any suggestions for this problem?

**Comment by AnthonyMDev** [comment]
It looks like this is not currently supported.

@cnoon I see two options here:
1. Add a new parameter for initialization of a custom `ImageDownloader`. This seems pretty easy, but then for each one of the user's UI elements they would need to manually set the `af_imageDownloader` property. That can get cumbersome to do every time.

2. We could make the `serverTrustPolicy` property in the ` NSURLSession` extension public in `Alamofire`. Then the solution would be `Alamofire.Manager.sharedInstance.session.serverTrustPolicy = myCustomPolicy`. Changing the policy on the singleton here can cause other issues, but seems like a feature that doesn't need to be touched by most people, but advanced users may want.

**Comment by cnoon** [comment]
We'll need to think through this use case a bit to make sure we get it right. Should easily be able to be solved in an elegant way. Self-signed certs just weren't taken into account when AFI was originally designed. I'm going to slate these changes for the 2.5.0 release. Once we get started on this @kusalshrestha we'll be sure to update the ticket.

Cheers. 🍻

**Comment by AnthonyMDev** [comment]
@cnoon I think this is part of a larger issue. Making any use of a custom `ImageDownloader` is cumbersome and frustrating. We should consider options to make that much easier and more elegant in the next version.

**Comment by cnoon** [comment]
Okay, finally had a chance to look into this a bit. My apologies for not getting back to everyone sooner. Long story short, you should be able to "easily" do everything you need without changing AFI in any way. Here's what you could do to make this work.

> I'm going to write this in Swift 3 since that's what I have open at the moment.

```swift
let sessionManager = SessionManager(
    configuration: ImageDownloader.defaultURLSessionConfiguration(),
    serverTrustPolicyManager: ServerTrustPolicyManager(
        policies: ["<-Invalid SSL url here->": .DisableEvaluation]
    )
)

UIImageView.af_sharedImageDownloader = ImageDownloader(sessionManager: sessionManager)
```

Nice and simple. It's only a few lines of code to set it all up. 

Now, @AnthonyMDev, to your point:

> Making any use of a custom ImageDownloader is cumbersome and frustrating. We should consider options to make that much easier and more elegant in the next version.

I'm afraid I don't see the complexity here. It's "literally" as simple as setting a single property on the `UIImageView` class. Were you thinking of some other limitation? I just want to make sure I'm not missing something really obvious. ☹️

Hopefully that helps shed some light here @kusalshrestha. Again my apologies for not getting back to you sooner. I'm going to go ahead and close this issue out for now since I think the example above should solve your issue. If not, please comment back and I'll be happy to re-open and investigate further.

Cheers. 🍻

**Comment by jsl303** [comment]
I'm on iOS 10.3.1, and I can't get it to work either. :( Could someone help? I'd really appreciate it.
let manager = SessionManager(configuration: URLSessionConfiguration.default, serverTrustPolicyManager: ServerTrustPolicyManager(policies:["10.0.1.19:4491":.disableEvaluation]))
manager.request("https://10.0.1.19:4491/action.html", parameters:parameters).authenticate(user:user, password:password).responseString {
 response in
 if let msg = response.result.value {
  debugPrint(msg)
 } else {
  debugPrint("No response")
 }
}

**Comment by AnthonyMDev** [comment]
@jsl303 Based on your sample code, this seems to be an `Alamofire` problem, not an `AlamofireImage` problem. I'm not exactly sure what is going on in your situation without more detailed information, but this seems to be a configuration problem, not an actual issue with the library. In that case, a GitHub issue is not the appropriate place to handle this. 

I'd suggest you create a StackOverflow question with some more details of the issue. (Include a more comprehensive code sample and more explanation of what problem you are having.) Be sure you tag the issue with the `alamofire` tag so that the Alamofire team is notified of your issue.

Good luck!

@cnoon Sorry I never replied to your point from back in September. You are right, I was mistakenly thinking that `af_imageDownloader` was an instance variable on `UIImageView`. As a class variable, this makes perfect sense and is easy to use.
