### ISSUE TITLE
Significant scroll lag with URLs containing long list of query parameters

### ISSUE THREAD

**Issue by philipengberg** [Alamofire/AlamofireImage#135]
### Issue
In a news feed like `UITableView` I have a `UITableViewCell` which literally only has a `UIImageView` to show an image, for which I use `AlamofireImage` to download.

In `cellForRowAtIndexPath(_:)` I simply use 
```swift
af_setImageWithURL(url, imageTransition: .CrossDissolve(0.25), runImageTransitionIfCached: false)
```
All is seems fine.

**However**, it turns out that passing a URL with a fairly long tail of query parameters (might just be the general length of the URL?) causes a **significant** lag in scroll performance on this line of code.

I have verified this by removing the tail of query parameters which results in a perfectly smooth scrolling experience.

An example of an image URL could be:
```
http://tonsser-development.imgix.net/simon-hjaere/D271B946-ABF3-4347-AB55-598A938DD7F9.jpeg?fit=min&fm=png&dpr=2&crop=faces&w=400&h=400
```

### Temporary fix
In order to reduce scroll lag, you sometimes need to off load computations to a background thread. I am **totally aware** that any update of the UI - like setting an image on an image view - should always happen on the **main thread**. However, doing the following completely mitigated the issue:
```swift
NSOperationQueue().addOperationWithBlock { [weak self] _ in
    self?.af_setImageWithURL(url, imageTransition: .CrossDissolve(0.25), runImageTransitionIfCached: false)
}
```

#### Or so I thought...

Turns out that this 'hack' works fine for **non-cached** images, but when I then have to set an image that has already been cached, weird things start to happen. Since I reset the image view in `prepareForReuse`:
```swift
override func prepareForReuse() {
    super.prepareForReuse()
        
    imageView.af_cancelImageRequest()
    imageView.image = nil
}
```
there is no image to show initially, but having the image in the cache should make it display virtually instantly. However, several seconds go by until the image is set. Of course this has to be due to the usage of a background thread to update the UI.
Super ugly 😑 

### Proposal

I currently see two paths from here:

1. We figure out why "long" URLs would cause this lag in the first place and fix it, or
2. We allow `af_setImageWithURL` to be initiated on a background thread, and then the implementation of this make sure to always set the image on the main thread (just like you already do with transitions on cached images).

Thanks 🙌

**Comment by philipengberg** [comment]
### Update

New investigations show that the lag only happens if the image is already cached.

**Comment by cnoon** [comment]
Hi @philipengberg,

Thank you for your detailed write-up of the issue you're seeing...much appreciated! Now as to the specifics here, this report seems a bit odd. We have an `iOS Example` app that should be able to demonstrate the issues you are seeing. Do you see performance issues in that app as well? I would assume not since we've spent a fair amount of time optimizing that app and we haven't seen these issues ourselves.

The sample app should be doing almost exactly what your report here is documenting. If we're going to continue to investigate here, we're going to need you to create a sample project demonstrating the issue, or modify our sample app to be able to produce the behavior you're seeing. Otherwise we won't be able to debug what's going wrong. Both reports of URLs being too long and it lagging when hitting the cache are not behaviors we're currently observing.

**Comment by philipengberg** [comment]
Of course @cnoon, that's totally fair. I will make an effort to reproduce with the sample app ☺️

**Comment by cnoon** [comment]
I'm going to close this issue out for now. If you end up providing a sample app which produces this behavior, I'll be happy to re-open and investigate further @philipengberg.

Cheers. 🍻
