### ISSUE TITLE
Image File Size  not always visible

### ISSUE THREAD

**Issue by grantkemp** [Alamofire/AlamofireImage#136]
Using this tool it doesn't seem to be possible to always get the file size.  Sometimes the file - Content-length header is visible - other times it doesn't get returned. 

Is there a way to consistently get the file image size for images that are downloaded via  `Alamofire.request(.GET, "imagePath")`

**Comment by cnoon** [comment]
Hi @grantkemp,

Unfortunately, it's not always possible for the server to compute the total payload size. When this happens, you don't receive a `Content-Length` header and the [expectedContentSize](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLResponse_Class/#//apple_ref/occ/instp/NSURLResponse/expectedContentLength) of the `NSURLReponse` will be set to `NSURLSessionTransferSizeUnknown` (which is -1). In these cases, you'll need to investigate if there's a way to get the server to return the `Content-Length` header, otherwise, you'll need to display progress as how much data has been downloaded so far without being able to tell them how much is left.

Cheers. 🍻
