### ISSUE TITLE
Set image in UICollectionViewCell with  af_setImageWithURL cost to much memory

### ISSUE THREAD

**Issue by riyanpratama** [Alamofire/AlamofireImage#155]
Hi,

I have some memory issue using AFI. I have `UICollectionView` with custom cell, and each cell has a `UIImageView`. In `cellForItemAtIndexPath`, I set that image with `af_setImageWithURL`. 

The problem is memory usage getting so high. If I set cell's image with local image, it only use 27Mb memory. But when I fetch image with `af_setImageWithURL`, memory usage are going about 87Mb.

So am I doing some mistake? 

Thank you.

**Comment by cnoon** [comment]
Nope, you're not making a mistake. Image loading causes your memory to increase. The ones loaded from an asset catalog are VERY optimized for rendering, whereas the ones downloaded are not and need to be inflated as well as having the pixel data rearranged for optimal performance when rendering to screen. Both of these result in your memory usage increasing for the downloaded images more than the local ones (increase is mainly due to inflation).

If you want to limit the memory usage of the caching system, you could set the `NSURLCache` memoryCapacity to zero. You could also set the `UIImageView`'s `AutoPurgingImageCache` capacity to something really low. This is not recommended though since the defaults are most likely what you want to be using.

Best of luck! 🍻

**Comment by riyanpratama** [comment]
Thank you so much, cnoon!

My problem is the resource that url provide is too big. Right now I handle it with resizing its image before placing in my UIImageView using filter.

```
let placeholderImage = UIImage(named: "app_default-resize")

let filter = AspectScaledToFitSizeFilter(size: self.imgProductItem.frame.size)
self.imgProductItem.af_setImageWithURL(
    url!,
    placeholderImage: placeholderImage,
    filter: filter
)
```

That's decrease so much memory usage. Again, thank you cnoon!

**Comment by cnoon** [comment]
You bet! Glad you got it figured out. 🍻
