### ISSUE TITLE
swift3 branch fails on Alamofire beta dependency

### ISSUE THREAD

**Issue by billburgess** [Alamofire/AlamofireImage#159]
I'm getting the following error when trying to use the swift3 branch for AFI. 

```
[!] Unable to satisfy the following requirements:

- `Alamofire (= 4.0.0-beta.1)` required by `AlamofireImage (3.0.0-beta.1)`

None of your spec sources contain a spec satisfying the dependency: `Alamofire (= 4.0.0-beta.1)`.
```

I've updated my spec repos, I've tried adding Alamofire directly, but they don't have a public facing podspec for the 4.0.0-beta.1 (now on beta.2). Am I missing something to correctly link to the swift3 version of this? I'm not using Alamofire at all other than the dependency for AFI.

**Comment by aumayr** [comment]
What worked for me (as a temporary solution) is explicitly pinning Alamofire to a specific commit:

```ruby
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :commit => '3cc5b4e8453bec9fd6b973d60e6b0605a38e4cf4'
    pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift3'
```

**Comment by GoldenJoe** [comment]
@aumayr That allows the cocoa pod to install, but Xcode fails to compile when I try to use AlamofireImage.

Command failed due to signal: Segmentation fault: 11

While type-checking expression at [/Users/GoldenJoe/Development/Xcode/Soapbox/Soapbox/Misc/SoapboxWebServices.swift:157:9 - line:160:9] RangeText="Alamofire.request(myURL, withMethod: .post, parameters: params, encoding: .url, headers: nil)
            .responseImage { response in
        }"

**Comment by cnoon** [comment]
Thanks @aumayr...I'm going to go ahead and close this issue out.
