### ISSUE TITLE
Resulting image of aspect scaling an image has size equal to the passed in size instead of the size the image was scaled to

### ISSUE THREAD

**Issue by rcbello** [Alamofire/AlamofireImage#164]
Hi,
About the method below, it returns an image with size equal to the passed in size parameter. Is this the expected behavior? I was expecting the resulting image to have the `scaledSize` as its size. If I'm not mistaken we can just use the`scaledSize` as the size of the context when we instantiate it to  achieve the behavior I was thinking.

```
public func af_imageAspectScaledToFitSize(size: CGSize) -> UIImage {
        let imageAspectRatio = self.size.width / self.size.height
        let canvasAspectRatio = size.width / size.height

        var resizeFactor: CGFloat

        if imageAspectRatio > canvasAspectRatio {
            resizeFactor = size.width / self.size.width
        } else {
            resizeFactor = size.height / self.size.height
        }

        let scaledSize = CGSize(width: self.size.width * resizeFactor, height: self.size.height * resizeFactor)
        let origin = CGPoint(x: (size.width - scaledSize.width) / 2.0, y: (size.height - scaledSize.height) / 2.0)

        UIGraphicsBeginImageContextWithOptions(size, false, 0.0)
        drawInRect(CGRect(origin: origin, size: scaledSize))

        let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return scaledImage
    }
```

**Comment by cnoon** [comment]
Nope, it was designed to work exactly as it does and has 100s of unit tests around it to ensure it does work exactly as you stated. If you tell the API I want an image of a certain size, it should return the image of that size, but modified in the way you specified in the API.

In this case, we're saying I want a 100x100 px image using an aspect fit. Therefore, we create a context of 100x100, and aspect fit the current image into that context. Any excess padding will be transparent if the original image was not square. This allows users to use any content mode they need to display the image rather than having to center the image if you don't pad it.

Hopefully that helps clarify things. If you insisted on removing the padding, it would be easy to add your own extension on `UIImage` that allowed you to do that.

Cheers. 🍻

**Comment by rcbello** [comment]
Ah yeah, I think I see it. Thank you for the reply.

**Comment by allaire** [comment]
@cnoon Hi Christian, Would it makes sense to include another method that specifies a max target size, and don't use transparent padding like the current method?

Currently a method in a `UIImage` extension like you said, but I think it would be something useful to have in AlamofireImage!

```
```    func resizeImage(targetSize: CGSize) -> UIImage {
        let size = self.size
        let widthRatio  = targetSize.width  / size.width
        let heightRatio = targetSize.height / size.height
        let newSize = widthRatio > heightRatio ?  CGSize(width: size.width * heightRatio, height: size.height * heightRatio) : CGSize(width: size.width * widthRatio,  height: size.height * widthRatio)
        let rect = CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height)
        
        UIGraphicsBeginImageContextWithOptions(newSize, false, 1.0)
        self.draw(in: rect)
        let newImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return newImage!
    }```
```

Thanks 🍻
