### ISSUE TITLE
How can we use the cancelRequestForRequestReceipt ? 

### ISSUE THREAD

**Issue by magen** [Alamofire/AlamofireImage#178]
Hey all, we are struggling to cancel request that sent already ..  ( i am not talking about cases when we want to cancel request because we already sent the same request ) ... i guess we need to use the methods: cancelRequestForRequestReceipt .. the problem is that it's not clear how to get this RequestReceipt. 
i will try to provide an example:
we have a collection view with different images ( each image have a different url ) .. if i will scroll back and forward fast , the method af_cancelImageRequest will do the job and will not create 2 active request for the same url .. Great !, the problem is when we try to scroll only to 1 direction and we have 100 images .. basically we want to be able to cancel the request that just sent but the image is not return, meaning we don't have the image and we don't AlamofireImage to continue with that request ...  ( cause by slow internet and fest scrolling ) .. 
So, if we got it right , we can use cancelRequestForRequestReceipt ... the problem is that we can't find how to get this RequestReceipt ... 

Help :)

**Comment by cnoon** [comment]
Hi @magen,

I don't understand why `af_cancelImageRequest` won't do what you want. That's how you cancel an image request on a `UIImageView`. All the request receipt logic is handled internally in the `UIImageView` extension.

I'd recommend you take a look at the [example app](https://github.com/Alamofire/AlamofireImage/blob/master/Example/ImageCell.swift#L71-L77) since it does exactly what you're trying to do. Most likely you need to implement `prepareForReuse` on your image cell.

```swift
    override func prepareForReuse() {
        super.prepareForReuse()

        imageView.af_cancelImageRequest()
        imageView.layer.removeAllAnimations()
        imageView.image = nil
    }
```

In the future, I'd recommend opening a question on [Stack Overflow](https://stackoverflow.com) for questions like this. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.

**Comment by magen** [comment]
Thanks ! i will open a question there right now :) 

BTW: i will attach my question link …  http://stackoverflow.com/questions/39437043/cancel-image-download-with-alamofireimage <http://stackoverflow.com/questions/39437043/cancel-image-download-with-alamofireimage>


----  
Magen Yadid | iOS Development Team Leader 
(m) +972-52-4235656 | Skype: magen_yadid  
OnO Apps - a+ people. a+ mobile. | onoapps.com <http://onoapps.com/>
