### ISSUE TITLE
Cannot import module 'AlamofireImage'

### ISSUE THREAD

**Issue by danielvivek2006** [Alamofire/AlamofireImage#184]
I've tried doing all the things specified in  [https://github.com/Alamofire/Alamofire/issues/441]

I still get this Error. 

I'm using Xcode 8 , with Cocoapods version : 1.0.1

**Comment by namdhis** [comment]
I have the same problem with you from i upgraded to 4.0.0 version. Don't understand!

**Comment by jshier** [comment]
Instructions on how to integrate AlamofireImage into your project are provided in our README. Unfortunately, due to the sheer number of differences between build environments we cannot provide individual integration support.

Therefore, these types of questions are best suited for [Stack Overflow](https://stackoverflow.com). We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
