### ISSUE TITLE
image in "binary/octet-stream"

### ISSUE THREAD

**Issue by SachinB17** [Alamofire/AlamofireImage#196]
using - AlamofireImage (3.0.0): @cnoon 

trying load image to UIImageView from url request which gives binary stream .
but fails with this error 

Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Alamofire.Result<UIKit.UIImage>>(bitPattern: 0x1178d2440)!.pointee)

 I have searched this already 
http://stackoverflow.com/questions/33876966/download-images-via-alamofireimage-framework-with-content-type-binary-octet-st

did this : 
let contentTypes: Set<String> = ["Content-Type", "binary/octet-stream"]
Request.addAcceptableImageContentTypes(contentTypes)

nothing works simply returns with error !! 

I have referred to previously closed issues : 
https://github.com/Alamofire/AlamofireImage/issues/60

Printing description of response.result.failure:

    fileprivate func urlRequest(with url: URL) -> URLRequest {
        var urlRequest = URLRequest(url: url)

//        for mimeType in DataRequest.acceptableImageContentTypes {
//            urlRequest.addValue(mimeType, forHTTPHeaderField: "Accept")
//        }
        urlRequest.addValue("image/*", forHTTPHeaderField: "Accept")
        return urlRequest
    }

still not working

▿ AFError
  ▿ responseValidationFailed : ResponseValidationFailureReason
    ▿ unacceptableContentType : 2 elements
      ▿ .0 : 11 elements
        - 0 : "image/tiff"
        - 1 : "image/x-win-bitmap"
        - 2 : "image/jpeg"
        - 3 : "image/x-icon"
        - 4 : "image/ico"
        - 5 : "image/gif"
        - 6 : "image/bmp"
        - 7 : "image/x-bmp"
        - 8 : "image/x-xbitmap"
        - 9 : "image/png"
        - 10 : "image/x-ms-bmp"
      - .1 : "application/octet-stream"

**Comment by jshier** [comment]
`application/octet-stream` is not an acceptable response type by default, as indicated in the error your printed. You can add it by using the `DataRequest.addAcceptableImageContentTypes` API provided for that purpose.

**Comment by johndpope-karhoo** [comment]
I think this error (which is not obvious it fails for some libraries / where logging of nserror is not switched on) is causing more pain for developers/testers than the downside of allowing this. I already wasted 2-3 days on this with testers complaining stuff doesn't work.

I suggest adding a parameter
restrictBinaryOctectStream = false by default

Then for users (a handful) who are worried their clients iPhones apps are going to be hacked some how by a s3 malformed binary executable which is going  cause a buffer overrun on a uiimage loading can switch this safety feature on if they desire. 

If this attack vector was ever surfaced know that Apple will hand over mad cash for the exploit. 
So everyone wins anyway.

**Comment by jshier** [comment]
Using `NSError` is no longer best practice in Swift 3, so those libraries need to refactor. Even when using `NSError` however, the description message of the `AFIError` should still be printed, so the cause of this error would still be clear. 

Ultimately though, the preset list of acceptable image types isn't about safety, it's about best practice, in that an image loading library should, by default, not load content that isn't an image. Attempting to do so should throw a clear error and the developer can then either add the missing content type or fix their backend to return the proper type.

So no, I don't think allowing arbitrary binary types is a good solution to this issue, as `application/octet-stream` isn't even the only one. @cnoon ?

**Comment by johndpope-karhoo** [comment]
Hi Jon,

thanks for getting back so fast.

I love Alamofire. I love AFNetworking. I love swift. I love objective-c. 

Some dude uploading image files to s3 server didn't specify the mimetype and now this library won't auto detect the file format. 

Should an image library make it's developers incur countless hours of troubleshooting (the defacto s3 out of the box mime type) for unacceptable image types? The total time wasted talking to QA / coworkers / product managers etc is quite time consuming. I have a ticket I can't close because AFNetworking won't load a file. Now we're debating whether to 
- include an external category 
- patch the library by changing the code in project.  
- fork the project / patch the project point Podfile to this other github project
- get the server administrator to re-upload the file(s)
- add more code to enable the content type. resubmit my 3rd pull request to get code merged.

Ultimately - I get that someone didn't do their job properly and s3 is co-contributor in this overall frustration. 

But consider this library could add more spoon feeding in the error message it is sending.
 
"application/octet-stream is not an acceptable image mime-type.  Please contact Amazon and tell them to autodetect the mime type. Or contact your system administrator and tell to reupload the file correctly and specify the correct mime-type. Alternatively - google the error and read through stackoverflow for the fix. "

Job done.

Or consider another approach could be.


"application/octet-stream is not an acceptable image mime-type.  Enable by setting 
enableS3UnacceptableBinaryFormats = true"

Where 
enableS3UnacceptableBinaryFormats = false by default

From my experience with AFNetworking -  there's no error message displayed using the setImage  and it's one of those try catch exceptions that gobbles the problem up into a black hole. https://github.com/AFNetworking/AFNetworking/issues/1827

Future readers of this 'closed' issue feel free to upvote this years from now.

**Comment by cnoon** [comment]
@jshier we should probably add that you can use `DataRequest.addAcceptableImageContentTypes` to add `application/octet-stream` if the error message. We could also add a small bit of info about configuring your server to return an image mime type. I little bit more verbosity here might go a long ways.

Thoughts?

**Comment by jshier** [comment]
If we want to go down that path, using `recoverySuggestion` for that information would probably be good. We should also then add it to all relevant AF and AFI errors.
