### ISSUE TITLE
Support for Query String Friendly Caching 

### ISSUE THREAD

**Issue by farice** [Alamofire/AlamofireImage#201]
Firstly, thanks for this awesome framework!

I have previously enjoyed the utility of both the imageDownloader and auto-purging cache, and the implementation of uniquely identifying each url request to avoid downloading the same image repeatedly. However, I've updated my backend to use query strings. Hence, the beginning of each request is identical, with a varying key at the end. This, of course, gets recognized as a new url request each time. I believe this to be a feature request to support uniquely identifying the beginning of a url request, in order to avoid transient keys. However, if an implementation exists to ameliorate this issue I appreciate your help! Thank you.

Faris

**Comment by cnoon** [comment]
Hi @farice,

Thanks for all the info here. I agree that it would be nice to have the `AutoPurgingImageCache` be a bit more flexible with what it considers a unique request to be. With that said, there's no way for AFI to know exactly what everyone considers to be unique for every type of request.

Because of this, I've opened up the `imageCacheKey` method in #203 to allow you to subclass `AutoPurgingImageCache` and override `imageCacheKey` to define your own system for determining uniqueness. This will allow everyone to completely customize the caching behavior for whatever `URLRequest` properties determine uniqueness for their APIs.

I'm going to close this issue out for now. Please redirect all further comments to #203.

Cheers. 🍻
