### ISSUE TITLE
Set download limit on UIImageView.af_sharedImageDownloader? 

### ISSUE THREAD

**Issue by danieldelouya** [Alamofire/AlamofireImage#207]
How do i do that?

**Comment by cnoon** [comment]
Hi @danieldelouya,

I'm not really sure what you mean by a download limit, but I'll try to guess. If you mean the total number of images you can add to the download queue, then no, there is no limit like that. You could easily implement one yourself before calling the `ImageDownloader` APIs.

Instead of adding a limit, the `ImageDownloader` manages an internal `lifo` or `fifo` queue which manages the number of active downloads. The number of active downloads controls how many image requests have actually been sent to the underlying URL session. It's important to not overload the URL session, otherwise you cannot reprioritize your requests. Currently, the default number of active downloads is 4 and that's certainly the recommended limit on iOS since a URL session can only handle 4 requests in parallel.

Hopefully that answers your question.

Cheers. 🍻
