### ISSUE TITLE
have questions of logical completion handler

### ISSUE THREAD

**Issue by cherishloveyou** [Alamofire/AlamofireImage#209]
have questions about the the func af_setImageWithURL's completion handler logic, it before self.image = image.  as UIImageView's extension, completion handler is the end of operation

**Comment by cnoon** [comment]
I completely agree @cherishloveyou. I believe this was due to legacy reasons and we never updated the calls once we didn't need to run this prior. I've just pushed up e59d18fa which addresses the ordering issue in both the `UIButton` and `UIImageView` extensions. It also fixes cases where the request was a duplicate which now calls the completion closure with a `requestCancelled` AFI error.

Cheers. 🍻
