### ISSUE TITLE
[Suggestion] Pause/Stop Image Downloader Queue

### ISSUE THREAD

**Issue by zaptrem** [Alamofire/AlamofireImage#211]
It would be useful to be able to stop the ImageDownloder queue when the user decides they don't need any more images. For example:

var downloader = ImageDownloader()
(Queue lots of images automatically (like for example when loading a list of product images)
downloader.stop()
(For use when moving to another page)

**Comment by danieldelouya** [comment]
+1

**Comment by cnoon** [comment]
You can do this already by collecting the `RequestReceipt` objects and using them in conjunction with the `cancelRequest` API.

```swift
class ExampleViewController {
    private let downloader = ImageDownloader()
    private var receipts: [RequestReceipt] = []

    func viewDidLoad() {
        let imageURLRequests: [URLRequest] = [
            "https://httpbin.org/image/jpeg",
            "https://httpbin.org/image/png"
        ].map { URLRequest(url: URL(string: $0)!) }

        receipts = downloader.download(imageURLRequests)
    }

    func viewWillDisappear() {
        receipts.forEach { downloader.cancelRequest(with: $0) }
    }
}
```

This is a much better approach than a blanket `stop` method because generally you are going to have other image requests that could be pending or still part of the queue from somewhere else that you don't want to accidentally cancel. This makes it explicit as to which request you actually intend to cancel.

Cheers. 🍻
