### ISSUE TITLE
i found some size error after the image saved to album 

### ISSUE THREAD

**Issue by bulolo** [Alamofire/AlamofireImage#233]
iphone 6

i find that if i use af_imageAspectScaled function to scale image,and save to the album,the image will create a 2 times size image 
it means if my image's size is 100 100 ,and i use  af_imageAspectScaled to scale image to 200 200,and i save to my album,i find my image's size is 400 400

```
CURRENT_ID_SIZE = CGSize(width: 200, height: 200)
var originalImage = UIImage(name:"photo")
 print(originalImage!.size)
//(100.0, 100.0)
var resultImage = originalImage.af_imageAspectScaled(toFill: CURRENT_ID_SIZE!)
 print(resultImage!.size)
//(200.0, 200.0)
```
but when i save the resultImage:
```
PHAssetChangeRequest.creationRequestForAsset(from: resultImage!)
```
it return me a (400 × 400) size image it created in my Album

when i save the originalImage :
```
PHAssetChangeRequest.creationRequestForAsset(from: originalImage!)
```
it return the (100.0, 100.0) size image  it created in my Album

**Comment by cnoon** [comment]
Hi @bulolo,

This is by design. The `UIImage(name: "photo")` method is returning you an image whose size is being reported as `(100.0, 100.0)` but has a scale of `2.0`. Therefore, the "actual" size of the underlying image is really `(200.0, 200.0)` when you consider the scale. When you then aspect scale the image to `(200.0, 200.0)` you are actually scaling the underlying image to `(400.0, 400.0)`. If you save that final image out, it will save as `(400.0, 400.0)` since a PNG or JPEG doesn't understand what "scale" is in regards to retina displays.

Hopefully that helps clarify things. In the future, I'd suggest you open a question on [Stack Overflow](https://stackoverflow.com) and tag `alamofire`. We use our GitHub project for bug reports and feature requests.

Best of luck! 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
