### ISSUE TITLE
Access images from disk cache without urlrequest

### ISSUE THREAD

**Issue by davidblaesing** [Alamofire/AlamofireImage#237]
How can i access disk cache with identifier `func image(withIdentifier:) -> Image?`? I was just able to access the disk cache with urlrequest `func image(for:) -> Image?`.

Setup
```swift
let imageCache = AutoPurgingImageCache()
// or let imageCache = UIImageView.af_sharedImageDownloader.imageCache
```
Launch application.
```swift
ImageDownloader.default.download(URLRequest(url: "urlToImage.jpg")) { response in
  imageCache.add(response.result.value!, withIdentifier: "test")
  imageCache.image(withIdentifier: "test") // Optional<Image>
}
```
Launch application again and run.
```swift
imageCache.image(withIdentifier: "test") // nil
```

**Comment by MJHelloWorld** [comment]
i also meet the same problem.

**Comment by cnoon** [comment]
Hi @davidblaesing,

The `AutoPurgingImageCache` is not an on-disk image cache, it is an in-memory image cache. The `ImageDownloader` is backed by a `URLCache` which is both an in-memory and on-disk cache based on the cache headers returned in the `HTTPURLResponse`.

In your example, your `urlToImage.jpg` is going to be most likely cached in the `URLCache`, but not the `ImageCache` at second launch. Therefore, if you do the following, it will be available in the `ImageCache` again.

```swift
ImageDownloader.default.download(URLRequest(url: "urlToImage.jpg")) { response in
  imageCache.add(response.result.value!, withIdentifier: "test")
}
```

In this case, the network request to fetch the image was not made because the image was loaded from the `URLCache` and appended into the image downloader's default image cache. We then directly added it to the custom image cache we've created.

For more information on how the cache's work and why they're designed the way they are, please see the [ImageCache](https://github.com/Alamofire/AlamofireImage#image-cache) and [ImageDownload Caching](https://github.com/Alamofire/AlamofireImage#image-caching) sections of the README.

Cheers. 🍻
