### ISSUE TITLE
UIImageView extension: cache doesn't work with URLRequestConvertible

### ISSUE THREAD

**Issue by johnnyoin** [Alamofire/AlamofireImage#242]
It seems that calling `af_setImage(withURL:)` on an UIImageView works very well, but calling `af_setImage(withURLRequest:)` doesn't save image to the disk. (The image is displayed but not cached)

I am using AlamofireImage 3.2.0

**Comment by cnoon** [comment]
Hi @johnnyoin,

Both APIs actually use the `af_setImage(withURLRequest:)` under-the-hood. If you are changing out the URL in the `URLRequest` then the image won't be cached, otherwise it will. Without more details here or example code, I don't think we can be of any further assistance. If you post some additional info, we can re-open and continue to investigate further if necessary.

Cheers. 🍻

**Comment by johnnyoin** [comment]
The problem came from the cache-control header of the response. Thank you very much and sorry for the inconvenience .
