### ISSUE TITLE
Not loading jpg images 

### ISSUE THREAD

**Issue by perlasivakrishna** [Alamofire/AlamofireImage#245]
I'm using image extension to download image and save it to cache. 

           imgview.af_setImage(withURL: URL(string:imageurl)!, placeholderImage: UIImage.gifImageWithName("PlaceHolder"), completion: {
                response in
                
                imgview.image = response.result.value
                
                imgview.contentMode = .scaleAspectFill
                
                
            })

for jpg images i'm getting  response.result.value as nil,   shall i need to add acceptablecontent types to the request. if so how to add that in above request 

Thank you

**Comment by perlasivakrishna** [comment]
I found it working by adding this line.
            let typereq = DataRequest.addAcceptableImageContentTypes(["image/jpeg","image/png","image/jpg","image/gif"])

1.But why these are not supporting defaultly ?., as they are the coomon type of images. 
2. Even though i pass gif in "addAcceptableImageContentTypes", my gif image is not loading.

Thank you.

**Comment by jshier** [comment]
`image/jpeg`, `image/png`, and `image/gif` are all supported content types. `image/jpg` is not, as the proper type for JPEG images is `image/jpeg`. Also, in my tests, GIFs loaded just fine, though they don't animate due to the limitations of `UIImageView`.

In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofireimage`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
