### ISSUE TITLE
Couldn't fetch image for specific url

### ISSUE THREAD

**Issue by ashirvad358** [Alamofire/AlamofireImage#248]
Below specific url is not downloading.

    let myUrl = URL(string: "https://s3-ap-south-1.amazonaws.com/addadocumentsmumbai/mum/brk/gallery/3380/1489821534-IMG-20170316-WA0025.jpg")

    myImageView.af_setImage(withURL: myUrl)

However the same is working using Haneke library.

    myImageView.hnk_setImage(from: myUrl)

**Comment by jshier** [comment]
Most likely (I haven't confirmed) this is due to the response using the `image/jpg` content type, which isn't supported by default, as `image/jpeg` is the proper response type for JPEG images. You can add this response type to the acceptable types using the `addAcceptableImageImageContentTypes(_:)` API on `DataRequest`.

In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofireimage`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
