### ISSUE TITLE
Unclear documentation setting disk and memory cache limits

### ISSUE THREAD

**Issue by peterwarbo** [Alamofire/AlamofireImage#268]
I can't really seem to find in the documentation how to setup the limits for both disk cached images and in-memory cached images with AlamofireImage.

Let's say I want to use 20 mb in-memory cache and 10 mb disk cache. How would I set that up?

I use the UIImageView extension `imageView.af_setImage(withURL: imageUrl)` to download images.

Also I'm not using image filters so I read something that you should set

```
let downloader = UIImageView.af_sharedImageDownloader
let configuration = downloader.sessionManager.session.configuration
configuration.urlCache?.memoryCapacity = 0
```

**Comment by jshier** [comment]
Our [caching documentation](https://github.com/Alamofire/AlamofireImage#image-caching) lays this out pretty clearly. However, your issue here is that you're trying to mutate a `URLSessionConfiguration` that's already been set, which doesn't work, per Apple's documentation. If you want to customize the caching in the `UIImageView` extension, you'll need to create your own `ImageDownloader`, as outlined in the [documentation](https://github.com/Alamofire/AlamofireImage#image-downloader). 

In general, you can accomplish the caching you want either by setting up a custom `URLCache` instance, or by limiting the `URLCache` to disk caching and use the `AutoPurgingImageCache` to do the memory caching, since it will also cache any image manipulations you do.

**Comment by Stunner** [comment]
I found specifying:

```
NSURLCache *URLCache = [[NSURLCache alloc] initWithMemoryCapacity:4 * 1024 * 1024
                                                       diskCapacity:20 * 1024 * 1024
                                                           diskPath:nil];
  [NSURLCache setSharedURLCache:URLCache];
```
as per https://nshipster.com/nsurlcache/ to work well (I was interested in caching response data, but this should work for images as well).
