### ISSUE TITLE
Image is not updating with the same image url

### ISSUE THREAD

**Issue by ajay2c9** [Alamofire/AlamofireImage#299]
Hi,
I am using AlamofireImage in my project. I am displaying the image in the ImageView using the below code.
profilePicImageView.af_setImage(withURL: URL(string: URL+profilePicName)!, placeholderImage: UIImage(named:"ProfileImage"))
First time the image is displaying fine, After that i updated the image in url. then the updated image with the same name of previous image. Then it is not updated in the imageView. Previous image is displaying .If i check the url in the browser. It is displaying the latest image.even though i removed the instance of my App and check. some times it is not updating. How to display the latest image in the imageUrl using the AlamofireImage.

**Comment by kikillers** [comment]
+1

**Comment by BilalPervez** [comment]
@ajay2c9 same issue in my app did you resolve it ? any update

**Comment by michzio** [comment]
Images are cached, but how to clear this cache?

**Comment by MarcSteven** [comment]
@michzio  I think you should take a look into the source code -ImageCache class, there are lots of method to remove image  from Cache ..
`/// Removes all images stored in the cache.
    ///
    /// - returns: `true` if images were removed from the cache, `false` otherwise.
    @discardableResult @objc
    open func removeAllImages() -> Bool {
        var removed = false

        synchronizationQueue.sync {
            if !self.cachedImages.isEmpty {
                self.cachedImages.removeAll()
                self.currentMemoryUsage = 0

                removed = true
            }
        }

        return removed
    }
`

**Comment by cnoon** [comment]
The reason the image is not being removed and replaced with the new one is that your original image you downloaded has not expired in the cache. It all depends on the `Cache-Control` headers and all the other caching headers that are set on the image response. AlamofireImage leverages the `URLCache` to handle all on-disk caching which uses the `Cache-Control` headers to control eviction. 

If you want this to work as expected with AlamofireImage, then you will need to publish the image to a different URL rather than reusing the same one. If you MUST continue to use the same URL, then you'll need to set the `Cache-Control` headers to not actually cache the image. Another option would be to use `E-Tags`, but AFI does not currently support etags.
