### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Naruone** [Alamofire/AlamofireImage#304]
<img width="939" alt="ss" src="https://user-images.githubusercontent.com/6942348/35427603-671781f0-02a5-11e8-9106-d0735f8a20eb.png">

swipe to bottom is ok, there is problem swiping up

**Comment by jshier** [comment]
You're likely crashing because of the force unwrapped `URL`. I suggest you handle it more safely.

We use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on [Stack Overflow](https://stackoverflow.com) and tag `alamofireimage`.

Cheers. 🍻

---

From our [Contribution Guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md)

## Asking Questions

We don't use GitHub as a support forum. For any usage questions that are not specific to the project itself, please ask on [Stack Overflow](https://stackoverflow.com) instead. By doing so, you'll be more likely to quickly solve your problem, and you'll allow anyone else with the same question to find the answer. This also allows maintainers to focus on improving the project for others.
