### ISSUE TITLE
af.setImage filter not working

### ISSUE THREAD

**Issue by martheli** [Alamofire/AlamofireImage#316]
I am trying to get af.setImage to work with the filter to populate the imageView of each basic tableView cell with a rounded photo.

## What did you expect to happen?

I expect each photo to be downloaded from internet and then populate into the standard imageView of each cell.

## What happened instead?

I get an error saying the imageView can not be 0. I put a check in and then ran it again and you can see the results here:

<img width="440" alt="screen shot 2018-06-17 at 3 36 33 pm" src="https://user-images.githubusercontent.com/20176169/41511439-b318c050-7244-11e8-8295-dac7f269480c.png">

The first page of results do not round the photos since the imageView is set to 0 size and then as I scroll, they get adjusted and round out. The code that I have in my UIImageView extension is as follows:

```
   if self.frame.height > 0 && self.frame.width > 0 {
        
            self.af_setImage(withURL: newUrl!, placeholderImage: placeholderImage, filter: filter)
            
        } else {
            
             self.af_setImage(withURL: newUrl!, placeholderImage: placeholderImage)
        }
```

It looks like the filter is trying to be applied to the imageView before the image gets downloaded so the imageView doesn't exist. In my cellForRow I just have the following:

`cell.imageView?.downloadFromUrl(url: url)`

So it should wait until the image gets downloaded before applying the filter and then setting it in the cell.

## Alamofire Environment

**Alamofire version:** 3.3.1
**Xcode version:** 9.4
**Swift version:** 4.1

**Comment by Vinzius** [comment]
Hey martheli,

I think you didn't get any feedback yet because your issue isn't related to the library, but how you implemented it.

Your problem is that your image is downloaded (or taken from cache) before the image view could have its frame setup.

Suggestion : avoid `if self.frame.height > 0 && self.frame.width > 0`. If you use a rounding filter (unrelated to the image size I think) you don't need it. If you need to resize the image first, then set a default/hard-coded image size.

You probably should post this issue on stackoverflow instead of here.

Cheers

**Comment by jshier** [comment]
@martheli @Vinzius is correct, it's likely you're attempting to capture these values before your cells are laid out, result in no apparent filtering. Either ensure your cells come pre-laid out (like from a XIB), or you need to pass the intended size to your image loading.
