### ISSUE TITLE
Request: Optional URL/URL Request parameters

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/AlamofireImage#40]
Could we make the URL/URL Request parameters optional on the `setImageWith...` methods?

I know this seems like it doesn't make sense at first, but I have a use case.

I'm using this library with a `UImageView` contained inside a `UITableViewCell`. My image url property on my model object is an optional, and if I don't have an image url to display, I'd like to display the placeholder image. In this case, if I have to do the following currently:

````
func setImageFromModel(modelObject: MyModel) { 
    guard let imageURL = modelObject.primaryImageURL else {
      imageView.image = modelObject.placeholderImage
      return
    }
    
    imageView.af_setImageWithURL(imageURL,
      placeholderImage: post.primaryImagePlaceholderImage,
      filter: nil,
      imageTransition: .CrossDissolve(0.2),
      completion: nil)
}
````

If the `URL` parameter was optional, this could be done just the one method call.

I'd be happy to make a PR, but I wanted to get input from @cnoon on this before I started.

**Comment by cnoon** [comment]
While I understand it would be more convenient for your @AnthonyMDev, I don't think this is a good change to make for the community. It introduces additional complexity that is difficult to explain to users. The `placeholderImage` should always be used as a placeholder, otherwise we're going to create confusion no matter how awesome our documentation is.

Thanks for the suggestion!
