### ISSUE TITLE
Add support for LCR images (tvOS)

### ISSUE THREAD

**Issue by jeffbowen** [Alamofire/AlamofireImage#46]
I'm unable to load [LCR images](https://developer.apple.com/library/prerelease/tvos/documentation/General/Conceptual/AppleTV_PG/CreatingParallaxArtwork.html) from my server in my tvOS app using `af_setImageWithURL`. [Asked about it on StackOverflow](http://stackoverflow.com/q/33354647/426839) to see if I was just doing something wrong but haven't gotten a response. My hunch is some work may need to be done to AlamofireImage (or its documentation) to handle LCR images.

**Comment by cnoon** [comment]
AlamofireImage currently does not support LCR images, but it is already in the backlog in our Trello project. We'll certainly be adding support for this feature sometime in the near future, but we do not have any hard dates around it yet. Once we know more, we'll be sure to comment back on this issue. 👍🏼

**Comment by cnoon** [comment]
If anyone out there wants to get rolling on this and submit a PR, that would be awesome!

**Comment by cnoon** [comment]
Hi @jeffbowen,

Apologies for taking so long to get back to you here. I just created an LCR image, uploaded it to Dropbox, and was able to turn it into a `UIImage` using AlamofireImage. The only thing you need to do is make sure that you add the appropriate `Content-Type` to the `DataRequest` extension if it's not already one of the supported types.

My quick example required me to add the `text/plain` content type since that's what Dropbox was serving up.

```swift
func testLCRImage() {
    let expectation = self.expectation(description: "test")
    let urlString = "https://dl.dropboxusercontent.com/u/2975688/Github/image.lcr"

    DataRequest.addAcceptableImageContentTypes(["text/plain"])

    Alamofire.request(urlString).responseImage { response in
        debugPrint(response)
        expectation.fulfill()
    }

    waitForExpectations(timeout: timeout, handler: nil)
}
```

Cheers. 🍻
