### ISSUE TITLE
Effect applying callback

### ISSUE THREAD

**Issue by staticdreams** [Alamofire/AlamofireImage#57]
I'm getting remotely displaying pretty large images on the screen (tvOS) - about 1920x1080.
The downloading process is pretty seamless (around 1 sec), but when I'm trying to apply a filter on top of it (``BlurFilter`` in my case), the time to actually display image on the screen multiplies by a factor of 6! And thats just on my mac. On actual Apple TV this will probably be longer. Well, I could just block the screen at this point and display a spinner, but is there a way to know when the filter is actually applied and the image is presented on the screen?

**Comment by Appsido** [comment]
To overcome this i tried to use imageDownloader to pre-fetch large images with a BlurFilter and then when i show the screen that uses the pre-fetched image i load it from NSCache. But unfortunately, the saved image in NSCache is original one, not the filtered one. Is this a library issue ? If the pre-fetched images with filters are save with filters applied that would overcome @staticdreams issue also

**Comment by cnoon** [comment]
Sorry for the delay here. You questions are perfectly valid, but I can say that AlamofireImage is functioning exactly as it should in these cases. The `BlurFilter` is really slow because CoreImage is just really slow at generating the blur effect. There are other methods out there for generating blurred images which could be built into their own custom `ImageFilter`. If you need a speedy blur @staticdreams, then the `BlurFilter` is probably not what you want.

@Appsido, your statement doesn't quite make sense. There is no `NSCache` in AlamofireImage. There is an `ImageCache` protocol and a concrete `AutoPurgingImageCache` implementation. There is also an underlying `NSURLCache` that supports the `NSURLSession` in the `ImageDownloader`. By default, the `ImageDownloader` will put the filtered image into the `AutoPurgingImageCache` for you. Then, if you need to manually retrieve it, you can do so by passing in the URLRequest and the filter identifier.

Hopefully that clears things up for both of you. If you have any further questions about this, please feel free to comment back on this issue.

Best of luck to you both! 🍻

**Comment by Appsido** [comment]
@cnoon sorry for the mistake regarding the mechanism used for caching images.
@staticdreams i did managed the blur effect with the following snippet. It may help you.

self.fullImage.af_setImageWithURL(URL, placeholderImage: nil, filter: nil, imageTransition: UIImageView.ImageTransition.None) { (image) -> Void in
            let blurEffect = UIBlurEffect(style: UIBlurEffectStyle.Dark)
            let blurEffectView = UIVisualEffectView(effect: blurEffect)
            blurEffectView.frame = CGRectMake(0, 0, UIScreen .mainScreen().bounds.width, UIScreen .mainScreen().bounds.height)
            self.fullImage.addSubview(blurEffectView)
        }
