### ISSUE TITLE
Failed image load in cell reuse other cell's image

### ISSUE THREAD

**Issue by allaire** [Alamofire/AlamofireImage#58]
I was testing my comments' tableview listing with a user that has a broken image in the cell (Failed to load resource: the server responded with a status of 403), and when I was scrolling, the user with the broken image was assigned with another user's image in the listing. This does not happen when there's no 403 error on any image. I was previously using HanekeSwift and this was not happening, and none of my code has change.

I'm using vanilla UIImageView extension:

```swift
cell.pictureImageView.af_setImageWithURL(NSURL(string: urlString)!, imageTransition: .CrossDissolve(0.2))
```

This is nothing major, but wondering if it's fixable, either on my side or on AlamofireImage's side.

Thanks!

**Comment by allaire** [comment]
I had to go back to HanekeSwift, AlamofireImage was too instable, sometimes my images would stop loading altogether.

**Comment by cnoon** [comment]
Hi @allaire, apologies for not getting back to you sooner. Your issue with that image is certainly due to an invalid MIME type. AlamofireImage has support built in for that already. You just need to specify the custom MIME type that needs to be supported.

```swift
Alamofire.Request.addAcceptableImageContentTypes(["image/jpg"])
```

As for your 403 issue...I still need to dig in a bit more.

**Comment by cnoon** [comment]
As for your 403 scenario, I can't see anything specific that stands out as to what could be a problem with the current logic. We have many tests built around the error handling, so I know the common cases are very well covered.

If you're triggering some race condition that we currently don't have properly tested, the only way I could help you work through it would be to have a sample app that demonstrates the problem. We haven't seen that type of behavior in the sample app, but I'm sure you're doing things differently.

Would it be possible for you to submit a sample app? Otherwise I'm afraid there's nothing else I can do at the moment to help you track down the issue further.

I'm going to go ahead and close this issue out for now. If you do end up posting more info, I'd be more than happy to re-open this issue.

Cheers. 🍻

**Comment by allaire** [comment]
Hi Christian,

No worries about not getting back any sooner, this is open source and I know you have a life outside of it :)

Will try everything you mention above.

Thanks!

**Comment by allaire** [comment]
@cnoon Just had this issue again with an image with a MIME type I wasn't supporting.

When there's an image with a MIME type that is not part of `acceptableImageContentTypes`, the image does not show up. It seems to create a problem in a Tableview, where when an image isn't showing up, it messes up all the other images order in the other cell (user get other user's profile picture).

I'm doing something like that in `cellForRowAtIndexPath`:

```
        if let pictureThumbUrl = comment.member.profile.pictureThumbUrl {
            cell.pictureImageView.setImageWithURL(pictureThumbUrl)
            cell.initialsLabel.hidden = true
        } else {
            cell.pictureImageView.image = nil
            cell.initialsLabel.hidden = false
        }```

Is there a method to know when the picture isn't `nil`, but has a MIME type that isn't supported?

**Comment by abrahamduran** [comment]
Hi guys, I am facing a similar situation. I am unsure whether this is a bug in the library.
I am using AlamofireImage to load images in reused cells (same situations as described here), but I am receiving this error: `Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 406)`

The weird thing is that I have tried to request the same image with Postman and some browsers, and so far they load the image just fine.

I tried using the `DataRequest.addAcceptableImageContentTypes(["image/jpg"])`, but proved to be unhelpful. And also tried using all the request being sent in a different environment (Postman, browsers, and curl) without success.

Should I open this as a bug? (tagging users involved in this issue): @cnoon @allaire

Below there are some useful details:

### Code
Caller:
```
if let url = media.thumbnailURL {
    logoImageView.setImage(with: url)
}
```
Extension:
```
import Foundation
import AlamofireImage

extension UIImageView {
    func setImage(with url: URL, placeholderImage: UIImage? = nil, completion: (() -> ())? = nil) {
        af_setImage(withURL: url, placeholderImage: placeholderImage, imageTransition: .crossDissolve(800))
        { _ in completion?() }
    }
}
```

### Sample URLs

- http://cdn.v.photoshelter.com/video-get/VD000aY3x2Q6xMuc/sec=wd0sd0oe0ed20181030R6rraPtN7LuvsrN/fmt=poster
- http://cdn.v.photoshelter.com/video-get/VD000Ev0w2bYo1Gc/sec=wd0sd0oe0ed20181030lVlIZwtdT2Dbgrb/fmt=poster
- http://cdn.v.photoshelter.com/video-get/VD000w4GIuykpA4w/sec=wd0sd0oe0ed2018103014R1DEWoTQ6Hpd4/fmt=poster

### Environment
Xcode 10.0
Swift 4.2
Alamofire 4.7.3
AlamofireImage 3.4.1

**Comment by Dev-** [comment]
@abrahamduran [SO Question](https://stackoverflow.com/questions/64281067/how-to-add-a-mime-type-to-alamofire-5-2)
