### ISSUE TITLE
UICollectionView multiple cells and images

### ISSUE THREAD

**Issue by fatihyildizhan** [Alamofire/AlamofireImage#76]
I am downloading multiple images in UICollectionView. There are about 30 cells on the screen. 
When I scroll to down and scroll to top back all images look like downloading again. They are slowly loading one by one.

Also I am getting this warning.
```
[/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI/CoreUI-371.4/Bom/Storage/BOMStorage.c:522] <memory> is not a BOMStorage file.
```

My Code:
In UICollectionViewCell
```
func loadImage(urlString: String) {
    CircleImageView.af_setImageWithURL(NSURL(string: urlString)!, 
     placeholderImage: UIImage(named: "holderImage"), 
     filter: CircleFilter())
}
```
What am I missing?

Note: I am using different Image/Cache library and it's working without any of these things.

Thanks

**Comment by patchthecode** [comment]
i am also getting this error: [/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI/CoreUI-371.4/Bom/Storage/BOMStorage.c:522] <memory> is not a BOMStorage file.

whats up with that?

**Comment by fatihyildizhan** [comment]
I am getting that error only this page. So, I thought it can be related with my real problem.

**Comment by jorjuela33** [comment]
looks like is a harmless message https://forums.developer.apple.com/thread/21723

**Comment by jshier** [comment]
@fatihyildizhan Depending on the sizes of your images it's possible you may be exhausting the memory cache that AlamofireImage provides by default. This is especially possible since the cache store the inflated image data, which can be quite large depending on the size of the image. If you want to customize the cache rules or size, you can provide your `ImageDownloader` instance to the `UIImageView.af_imageDownloader`. [Follow the README](https://github.com/Alamofire/AlamofireImage#image-downloader) to learn how to build your own downloader and customize the caching behavior.
