### ISSUE TITLE
Unnecessary API method definitions?

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/AlamofireImage#80]
As I started working on a PR for #48, I started thinking about all of these method definitions that seem unnecessary. 

For example:
`public func af_setImageWithURL(URL: NSURL, placeholderImage: UIImage? = nil)`
and
`public func af_setImageWithURL(URL: NSURL, placeholderImage: UIImage? = nil, filter: ImageFilter)`

Since we have the ability to give parameters default values in Swift, these could be combined into one function:
`public func af_setImageWithURL(URL: NSURL, placeholderImage: UIImage? = nil, filter: ImageFilter? = nil)`

Is there a reason that I'm not seeing why all of these functions exist? It would make the APIs much cleaner to remove than and just use default parameter values. Keeping all these functions also makes it much harder to add new features. 

While trying to add the `progress` parameter for #48, I'm finding that the number of combinations of the function definitions we need to handle this is growing far too large.

**Comment by AnthonyMDev** [comment]
I've created a pull request for this refactor already. #81

**Comment by cnoon** [comment]
This is a great question @AnthonyMDev. The variations were originally created to make it easier to pick the exact API you wanted in auto-complete. That approach continues to lose popularity as more and more people learn how to write Swift. I think it's probably time to squash down those APIs as well. I'm assuming #81 contains two APIs, one that takes a URL, and one that takes a URLRequestConvertible.

I'm going to close this out for now since I'm guessing that answers your question. Happy to re-open if necessary. 🍻
