### ISSUE TITLE
Extra argument 'timeline' in call

### ISSUE THREAD

**Issue by hsavit1** [Alamofire/AlamofireImage#86]
hello,

i've just installed the latest version of AlamofireImage via Cocoapods. in the ImageDownloader.swift file I'm getting an error

Extra argument 'timeline' in call

```
                            dispatch_async(dispatch_get_main_queue()) {
                                let response = Response<Image, NSError>(
                                    request: response.request,
                                    response: response.response,
                                    data: response.data,
                                    result: .Success(filteredImage),
                                    timeline: response.timeline
                                )

                                completion?(response)
                            }
```

any ideas?

**Comment by hsavit1** [comment]
I believe this was a versioning issue. Upon upgrading to AlamoFire 3.2 this should go away. Closing

**Comment by cnoon** [comment]
This is actually an issue with the AFI 2.3.1 podspec. I forgot to bump the Alamofire dependency to `~> 3.2` which is why you ran into this. I've just submitted https://github.com/CocoaPods/Specs/pull/13816 to resolve the issue for everyone else. Thanks for opening this so I knew there was an issue!

Cheers. 🍻
