### ISSUE TITLE
Requested images being downsampled by default

### ISSUE THREAD

**Issue by bdrelling** [Alamofire/AlamofireImage#89]
I recently made the switch from Kingfisher to AlamofireImage in keeping with using as many of the amazing Alamofire tools I can. Having a slight issue with image scaling...

I can't figure this out and have poured over the documentation. I understand how scaling works and how device size works, but AlamofireImage is scaling the images I request unlike any other library and I don't know how to change that.

If I request an image from the URL `"https://placehold.it/80x80"`, I expect it to be a `UIImage` with a size of `80x80` at a scale of `1`. I want to work with it at this size on purpose, because I'm requesting it at the size I need. 

If I use `KingfisherManager.sharedManager.retrieveImageWithURL`, my image comes back with a `scale` of `1`. 

Similarly, this is the behavior from `SDWebImage` when I had my Objective-C application.

AlamofireImage's `ImageDownloader.defaultInstance.downloadImage` is giving me a `scale` of `2`.

I know that I could create a new context and scale it back to 80x80, but this sort of defeats the purpose.

The images renders 100% as expected on either of the other two libraries when the scale is not changed. 

The same image in my library at `160x160` is `7.7kb`, vs. the `80x80` image being only `400b`. This is a very important use case for the app.

Let me know if I'm doing something wrong. I assume there's a filter or setting I can set to make it not scale my image automatically but can't seem to find it.

Thanks!

**Comment by cnoon** [comment]
Hi @bdrelling,

Thanks for the detailed description. Much appreciated! It makes it much easier to work through an issue with some context. Let's get going.

First off, the goal of AlamofireImage is not to mimic `Kingfisher` or `SDWebImage`. I'm sure you understand that, but I wanted that to be clear. Secondly, the images are not being downsampled, they are just being represented with an additional scale factor. The same UIImage at 160x160x@1x and 80x80x@2x are still the same image. They just make it easier to work with points in terms of UIKit operations.

AlamofireImage was designed from the beginning to support scale factors to attempt to make everyone's lives easier. By supporting scale factors, it makes things like rounding corners MUCH easier. For example, rounding the corners to a 20 pt radius is tricky when you have three different sized images all with a scale factor of 1. However, it is easy when you have three different images with the same size and scale factors of 1, 2 and 3.

So there's a bit of the reasoning as to why it is the way it is currently. What would be helpful from you is if you could describe what the issue is that you're having because of this behavior. The only thing you've pointed out so far from what I can tell is the following:

> The same image in my library at 160x160 is 7.7kb, vs. the 80x80 image being only 400b. This is a very important use case for the app.

This isn't enough to go on yet. Happy to help, but need more info.

Cheers. 🍻

**Comment by bdrelling** [comment]
@cnoon Thanks for the reply.

Totally understandable that it isn't meant to mimic `Kingfisher` or `SDWebImage`. I'm trying to use the full `Alamofire` suite of tools to keep everything consistent.

To start with my specific issue, I'm working with `GoogleMaps` iOS SDK. The base size of the pin icon that I want is `40x40`. For my marker image, I multiply that size by my screen scale, so I request it from my CDN at `80x80`. 

`Kingfisher` returns the image to me at `80x80` with a scale of 1. When I take that image and put it into `GoogleMaps`, it displays it at `40x40`.

`Alamofire` returns the image to me at `40x40` with a scale of 2. When I send this image to `GoogleMaps`, it displays the image at `20x20`. 

Similarly, on a 3x device (iPhone 6 Plus), I request an image at `120x120` which `Alamofire` gives me back at `40x40`, and `GoogleMaps` then scales that down again to `13.33`. 

As I mentioned, I was absolutely sure this was intentional on the part of the `Alamofire` framework, but I was hoping there was a way to tell it *not* to scale my image automatically in the instances where I'm expecting something to display at the size I'm requesting. Or rather, when I'm passing it off to a function or library to handle.

I don't know if I would consider this a `GoogleMaps` bug because I have seen this mentioned in documentation.

I also guess my followup question would be: Why do `Kingfisher` and `SDWebImage` choose not to scale the image? I would assume that scaling the image from a web request is really the most common expectation, but I'm not sure I totally understand why it would or would not be a user option at that point.

Sorry if anything I've said is vague or incorrect. 

Thanks for the help!

**Comment by cnoon** [comment]
Hi @bdrelling,

Thanks again for all the details...it really helps us give you better feedback. This time I have good news, you can already do exactly what it is you need to do with AlamofireImage! Here's a quick example of how you can adjust the image scale factor:

```swift
func testImageScaleAdjustment() {
    // Given
    let expectation = expectationWithDescription("should download")

    var image: Image?

    // When
    Alamofire.request(.GET, "https://httpbin.org/image/jpeg").responseImage(1.0) { response in
        image = response.result.value
        print(response)
        expectation.fulfill()
    }

    waitForExpectationsWithTimeout(timeout, handler: nil)

    // Then
    let size = image?.size ?? CGSizeZero
    let scale = image?.scale ?? 0.0

    print("Image Size: \(size), Image Scale: \(scale)")
}

// Outputs with no scale factor specified: 
//   - Image Size: (119.5, 89.0), Image Scale: 2.0

// Outputs with 1.0 specified: 
//   - Image Size: (239.0, 178.0), Image Scale: 1.0
```

The key is the `responseImage(1.0)` in the above example. That specifies a scale factor of `1.0` instead of defaulting to the `UIScreen` scale factor. Here's a look at the `responseImage` API:

```swift
public func responseImage(
    imageScale: CGFloat = Request.imageScale,
    inflateResponseImage: Bool = true,
    completionHandler: Response<Image, NSError> -> Void)
    -> Self
{
    // implementation...
}
```

This should easily be able to handle your use case. Thanks for all the details you provided here and my apologies for not putting this info in my first response.

Hope that helps! 🍻
