### ISSUE TITLE
Downloaded image is killing share extension

### ISSUE THREAD

**Issue by JamieWhite** [Alamofire/AlamofireImage#92]
Hey,

I'm using `af_setImageWithURL()` in my share extension for one image and when the image downloads the extension gets killed off. I'm assuming the image is too big because when I comment out the image setter it works fine. The image in question is this: https://www.raspberrypi.org/wp-content/uploads/2016/02/IMG_4090.jpg

I tried a number of things like playing with the imageDownloader and Cache but the extension keeps getting killed off.

I figured I need to get in the downloading process to check the contentSize then cancel the request. I couldn't find anything for this in AlamofireImage so I had to jump into vanilla Alamofire. The approach I'm going down at the moment is something like this: 

```Swift
Alamofire.request(.GET, path).responseImage(completionHandler: { response in
    switch response.result {
    case .Success(let image):
        self.imageView.image = image
        completion(completed: true)
    case .Failure:
        completion(completed: false)
     }
}).progress({ _, _, totalExpected in
    if totalExpected > Int64(self.maxImageSize) {
        self.request?.cancel()
    }
})
```

Any suggestions how to work around this?

What are your thoughts on my approach? My extension works with this but what Im wondering is how does this work with Alamofires cache?

**Comment by cnoon** [comment]
Looks like app extensions are going to get much less memory allowed memory usage than normal, so you'll need to be more careful with downloading your images.

* [Keyboard Extension](http://stackoverflow.com/questions/25354192/get-terminated-due-to-memory-error-for-ios-8-custom-keyboard-extension)
* [Photo Editing Extension](http://stackoverflow.com/questions/25404625/photo-editing-extension-needs-lots-of-memory-and-got-crashed-how-to-avoid-it)

Luckily, you have options here.

### Option 1
First off, you could set the `inflateResponseImage` parameter of `responseImage` to `false`. That would certainly decrease your memory footprint, although you'll take that hit once you render the image to the screen.

### Option 2
Another option would be to use `Alamofire.download` instead of `Alamofire.request`. This will download the image file to disk and move it to a location of your choosing. Then you could load the data from the file into an image and handle it that way.

---

Both of these approaches will greatly reduce your memory footprint. Now whether it will be enough or not, that I can't be certain of. Hopefully that helps.

Best of luck! 🍻
